Replacing geocoding exercise with palpatine api exercise
ambyint/full-stack-coding-challenge pull request #5
Opened 2019-05-31 20:05 UTC by ColinThompson1

2019-06-05 17:13 UTC, albchu approved these changes

2019-07-03 21:17 UTC, bradjabel requested changes
Looks good, just some minor changes

2019-07-03 21:17 UTC, bradjabel commented on palpatines-api/README.md
> +* Load the super-secret-data.txt file provided. Each line is a collection of citizen information to be decrypted
What do you think about changing `Each line is a collection of citizen information to be decrypted` to `Each line is encrypted information on a single citizen`?

Reading this again, using the word `collection` might lead candidates to think each line is an encrypted array. They would figure it out through trial and error, but I think this might be clearer.

2019-07-03 21:17 UTC, bradabelgit commented on palpatines-api/README.md
> +Be prepared to discuss how you might improve your program to handle  a galaxy with millions or even billions of unique
Change 

Describe any challenges that made the task more difficult Be prepared to discuss how you might improve your program to handle  a galaxy with millions or even billions of unique citizens and homeworlds

to 

Describe any challenges that made the task more difficult and how you might improve your program to handle a galaxy with millions of unique citizens and homeworlds. Be prepared to discuss this in the technical interview

2019-07-04 15:17 UTC, ColinThompson1 commented on palpatines-api/README.md
> +* Load the super-secret-data.txt file provided. Each line is a collection of citizen information to be decrypted
Yeah agreed

2019-07-04 20:24 UTC, bradjabel approved these changes
Looks good! We should find some other Ambyint devs to test this out

2020-03-09 21:55 UTC, merged